#!/bin/ash

# This script kexecs into the real system kernel from the
# initramfs environment. It is meant to be executed in the initramfs
# environment.
# This script uses the kexec_from_config script to do the actual
# work. Look in that script for further information on how this script
# works (for example, config file syntax and semantics).
# The config file for the boot/kexec is /boot/usb-boot-config.ash (in the
# root filesystem).

# Print an error message and exit if the script attempts to expand an unset variable.
set -u

# Path to the main system root in the initramfs environment.
MAIN_SYSTEM_ROOT=/sysroot
# Path to the config file relative to the main system root.
PATH_TO_CONFIG_FILE=/boot/usb-boot-config.ash
# Base of template name for temporary file that will contain
# combined initrd image.
COMBINED_INITRD_FILENAME_TEMPLATE=/combined_initrd_image

config_file_path="$MAIN_SYSTEM_ROOT/$PATH_TO_CONFIG_FILE"

/usr/local/lib/usb_initramfs/kexec_from_config "$config_file_path" "$COMBINED_INITRD_FILENAME_TEMPLATE" || exit 1
