#!/bin/bash

# This script reboots the system by kexec-ing into the boot kernel
# instead of fully rebooting the hardware.
# This script boots the kernel in accordance with the config file
# located at /boot/usb-boot-config.ash.
# It uses the kexec_from_config script as a backend, so see that
# script for more information on how this script works.
# This script executes kexec_from_config using bash, but that script
# was originally written to be run on busybox ash. It should be fine
# though, because the script is basically posix compliant.

# Print an error message and exit if the script attempts to expand an unset variable.
set -u

# Path to the config file.
PATH_TO_CONFIG_FILE=/boot/usb-boot-config.ash
# Base for template name for temporary file that will contain combined initrd image.
COMBINED_INITRD_FILENAME_BASE=/run/usb-boot/combined_initrd_image

bash /usr/local/lib/usb-boot/kexec_from_config "$PATH_TO_CONFIG_FILE" "$COMBINED_INITRD_FILENAME_BASE" || exit 1
