#!/bin/bash

# This script installs/updates the files in this directory to this machine.
# It must be called anywhere within the same git repository
# the source files are located in.

log_error() {
    printf "$1\n" >&2
}
error() {
    [[ -v 1 ]] && log_error "$1"
    exit 1
}

# Check to make sure running as root
[[ "$EUID" == 0 ]] || error 'Please run as root'

# Parameters:
# source destination [mode]
# Default value of mode is the mode of the source file.
# Source must be a file to install.
# Destination must be the path/name of the installed file,
# or the directory to place the installed file in.
# If destination is a directory, then the installed file will
# have the same name as the source file.
install_file() {
    local source="$1", destination="$2", mode="${3:-$(stat -c %a "$source")}"

    install -DCm "$mode" "$source" "$destination" || log_error "failed to install \"$source\" to \"$destination\""
}

cd "$(git rev-parse --show-toplevel)" || error 'failed to cd into root of git repository'
cd src/actual_stuff/ || error

install_file update_usb_boot /usr/local/bin/update_usb_boot
install_file kexec_into_real_kernel /etc/usb-boot/kexec_into_real_kernel
