#!/bin/bash

build() {
    set_user_passwords << EOF
root:
EOF
}

help() {
    cat << EOF
This hook disables the root password in the initramfs.
I.e. it sets the root password to empty.
This means it will be possible to login to the root account without
having to enter a password, e.g. when accessing the emergency console
during emergency mode.
EOF
}
