#!/bin/bash

build() {
    root_password="$(cat /etc/shadow | sed -n '/^root:/p' | head -n1 | cut -f2 -d:)"
    set_user_passwords -e << EOF
root:$root_password
EOF
}

help() {
    cat << EOF
This hook sets the root password in the initramfs image to be
the same as the root password on the main system.
EOF
}
